import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import postcssPlugin from "esbuild-postcss";
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";
import fs from "fs";
import path from "path";

// Minimal .env loader (avoids adding a dotenv dependency).
function loadDotEnv(file = ".env") {
	try {
		const content = fs.readFileSync(file, "utf8");
		for (const rawLine of content.split(/\r?\n/)) {
			const line = rawLine.trim();
			if (!line || line.startsWith("#")) continue;
			const eq = line.indexOf("=");
			if (eq === -1) continue;
			const key = line.slice(0, eq).trim();
			let value = line.slice(eq + 1).trim();
			if (
				(value.startsWith('"') && value.endsWith('"')) ||
				(value.startsWith("'") && value.endsWith("'"))
			) {
				value = value.slice(1, -1);
			}
			if (!(key in process.env)) process.env[key] = value;
		}
	} catch (err) {
		if (err.code !== "ENOENT") throw err;
	}
}
loadDotEnv();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Shared state to track build completions
let jsBuildComplete = false;
let cssBuildComplete = false;

// Function to run post-build steps after both builds complete
async function checkAndRunPostBuild() {
	if (jsBuildComplete && cssBuildComplete) {
		jsBuildComplete = false;
		cssBuildComplete = false;
		await postBuild();
	}
}

// Rebuild-notify plugin factory
function rebuildNotify(buildType) {
	return {
		name: "rebuild-notify",
		setup(build) {
			build.onEnd(async (result) => {
				if (buildType === "js") {
					jsBuildComplete = true;
				} else if (buildType === "css") {
					cssBuildComplete = true;
				}
				await checkAndRunPostBuild();
				console.log(
					`${buildType} build ended with ${result.errors.length} errors`
				);
			});
		},
	};
}

// JavaScript build options
const esbuildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
	plugins: [!prod && rebuildNotify("js")].filter(Boolean),
};

// CSS build options
const cssBuildOptions = {
	entryPoints: ["src/styles.css"],
	outfile: "main.css",
	bundle: true,
	sourcemap: false,
	plugins: [
		postcssPlugin({
			plugins: [tailwindcss, autoprefixer],
		}),
		!prod && rebuildNotify("css"),
	].filter(Boolean),
};

if (prod) {
	// Build JavaScript
	await esbuild.build(esbuildOptions);
	// Build CSS
	await esbuild.build(cssBuildOptions);
	// Run post-build steps
	await postBuild();
	process.exit(0);
} else {
	// Development mode with watch
	const context = await esbuild.context(esbuildOptions);
	await context.watch();

	const cssContext = await esbuild.context(cssBuildOptions);
	await cssContext.watch();
}

async function postBuild() {
	// Ensure main.css exists
	try {
		await fs.promises.access("main.css");
	} catch {
		throw new Error("main.css not found");
	}

	await replaceRemToPx("main.css");

	const cssContent = await fs.promises.readFile("main.css", "utf8");
	const jsContent = await fs.promises.readFile("main.js", "utf8");

	// Escape CSS so it's safe inside both template literals (dev build)
	// and double-quoted strings (after esbuild minifier rewrites it).
	const escapedCssContent = JSON.stringify(cssContent)
		.slice(1, -1)
		.replace(/`/g, "\\`")
		.replace(/\$\{/g, "\\${");
	const injectedContent = jsContent.replace(
		"/* INJECTED_CSS */",
		escapedCssContent
	);

	await fs.promises.writeFile("main.js", injectedContent);

	// Safely unlink files if they exist
	for (const file of ["main.css", "styles.css"]) {
		try {
			await fs.promises.unlink(file);
		} catch (err) {
			if (err.code !== "ENOENT") throw err;
		}
	}

	const customCss = `.infranodus-plugin-yellow-highlight { background-color: yellow !important; }`;
	await fs.promises.writeFile("styles.css", customCss);

	await deployToPluginDir();
}

async function deployToPluginDir() {
	const target = process.env.PLUGIN_DEPLOY_DIR;
	if (!target) return;

	try {
		await fs.promises.mkdir(target, { recursive: true });
	} catch (err) {
		console.warn(`[deploy] could not create ${target}: ${err.message}`);
		return;
	}

	const files = ["main.js", "styles.css", "manifest.json"];
	for (const file of files) {
		try {
			await fs.promises.copyFile(file, path.join(target, file));
		} catch (err) {
			console.warn(`[deploy] failed to copy ${file}: ${err.message}`);
		}
	}
	console.log(`[deploy] copied ${files.join(", ")} → ${target}`);
}

async function replaceRemToPx(path) {
	const cssContent = await fs.promises.readFile(path, "utf-8");
	const updated = cssContent.replace(
		/([\d.]+)rem/g,
		(_, val) => `${val * 16}px`
	);
	await fs.promises.writeFile(path, updated, "utf-8");
}
